<?php

if (!defined('ABSPATH')) {
    exit;
}

/*
|--------------------------------------------------------------------------
| Image Processor Init
|--------------------------------------------------------------------------
*/

function yio_image_processor_init()
{
    add_filter(
        'wp_generate_attachment_metadata',
        'yio_process_uploaded_image',
        10,
        2
    );
}

/*
|--------------------------------------------------------------------------
| Process New Upload
|--------------------------------------------------------------------------
*/

/**
 * Hook callback: runs the optimization pipeline for newly uploaded images.
 *
 * A static re-entrancy guard prevents infinite recursion, because the
 * pipeline itself calls wp_generate_attachment_metadata() internally to
 * regenerate size variants from the converted file.
 *
 * @param array $metadata      Attachment metadata generated by WordPress.
 * @param int   $attachment_id Attachment ID.
 * @return array
 */
function yio_process_uploaded_image($metadata, $attachment_id)
{
    /*
    |--------------------------------------------------------------------------
    | Re-entrancy Guard
    |--------------------------------------------------------------------------
    */

    static $in_progress = false;

    if ($in_progress) {
        return $metadata;
    }

    // Restore operations must not re-trigger the pipeline.
    if (yio_restore_active()) {
        return $metadata;
    }

    if (!is_array($metadata)) {
        return $metadata;
    }

    /*
    |--------------------------------------------------------------------------
    | Check Plugin Status
    |--------------------------------------------------------------------------
    */

    if (!yio_get_option('enabled', 1)) {
        return $metadata;
    }

    if (!yio_get_option('process_new_uploads', 1)) {
        return $metadata;
    }

    /*
    |--------------------------------------------------------------------------
    | Only Real Images
    |--------------------------------------------------------------------------
    */

    if (empty($metadata['width']) || empty($metadata['height'])) {
        return $metadata;
    }

    $mime = get_post_mime_type($attachment_id);

    if (!is_string($mime) || strpos($mime, 'image/') !== 0) {
        return $metadata;
    }

    /*
    |--------------------------------------------------------------------------
    | Get File
    |--------------------------------------------------------------------------
    */

    $file = get_attached_file($attachment_id);

    if (!$file || !file_exists($file)) {
        return $metadata;
    }

    /*
    |--------------------------------------------------------------------------
    | Skip Already Converted / Non-convertible Files
    |--------------------------------------------------------------------------
    */

    $current_ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
    $target      = yio_output_extension();

    if ($current_ext === 'gif' && yio_is_animated_gif($file)) {
        yio_log('Skipped animated GIF: ' . $file);
        return $metadata;
    }

    if ($current_ext === $target) {
        yio_log('Skipped, already ' . strtoupper($target) . ': ' . $file);
        return $metadata;
    }

    /*
    |--------------------------------------------------------------------------
    | Dry Run
    |--------------------------------------------------------------------------
    */

    if (yio_get_option('dry_run', 0)) {
        yio_log('DRY RUN: ' . $file . ' -> ' . $target);
        return $metadata;
    }

    /*
    |--------------------------------------------------------------------------
    | Optimize
    |--------------------------------------------------------------------------
    */

    $in_progress = true;

    try {

        $result = yio_optimize_single_image($file, $metadata, $attachment_id);

    } catch (Throwable $e) {

        yio_log('Optimization failed (' . $e->getMessage() . '): ' . $file);

        $result = $metadata;

    } finally {

        $in_progress = false;

    }

    return $result;
}

/*
|--------------------------------------------------------------------------
| Optimize Single Image
|--------------------------------------------------------------------------
*/

/**
 * The full single-image optimization pipeline.
 *
 * Backup original -> auto-orient -> smart resize -> watermark -> SEO
 * optimization -> convert to WebP/AVIF -> regenerate size variants ->
 * point WordPress at the new file -> remove old files.
 *
 * The old files are only deleted after the database has been updated
 * successfully, so a failure at any point leaves the original attachment
 * fully intact (conversion artifacts are rolled back).
 *
 * This function is also the entry point used by the bulk optimizer.
 *
 * @param string $file          Absolute path to the attached file.
 * @param array  $metadata      Existing attachment metadata.
 * @param int    $attachment_id Attachment ID.
 * @return array New attachment metadata.
 */
function yio_optimize_single_image($file, $metadata, $attachment_id)
{
    static $in_pipeline = false;

    // Re-entrancy guard: wp_generate_attachment_metadata() called inside
    // the pipeline re-fires the metadata filter. The upload hook sets its
    // own guard, but bulk mode calls this function directly, so without
    // this guard the nested filter call would re-run the whole pipeline.
    if ($in_pipeline) {
        return $metadata;
    }

    $in_pipeline = true;

    try {

        return yio_optimize_single_image_impl($file, $metadata, $attachment_id);

    } finally {

        $in_pipeline = false;

    }
}

/**
 * @internal Actual pipeline body; see yio_optimize_single_image().
 *
 * @param string $file
 * @param array  $metadata
 * @param int    $attachment_id
 * @return array
 */
function yio_optimize_single_image_impl($file, $metadata, $attachment_id)
{
    if (!file_exists($file)) {
        return $metadata;
    }

    $dir  = dirname($file);
    $base = pathinfo($file, PATHINFO_FILENAME);

    /*
    |--------------------------------------------------------------------------
    | Backup Original
    |--------------------------------------------------------------------------
    */

    if (yio_get_option('backup_original', 1)) {

        if (!yio_create_backup($file)) {
            yio_log('Backup failed, aborting: ' . $file);
            return $metadata;
        }

        // Also preserve the raw pre-scaled file, if WordPress created one.
        if (!empty($metadata['original_image'])) {

            $original_image = $dir . '/' . $metadata['original_image'];

            if (is_file($original_image)) {
                yio_create_backup($original_image);
            }
        }
    }

    /*
    |--------------------------------------------------------------------------
    | Optimize (rollback-safe section)
    |--------------------------------------------------------------------------
    */

    // Files created during conversion / size regeneration. Removed again
    // if anything fails, so the original attachment stays untouched.
    $created = array();

    try {

        /*
        |--------------------------------------------------------------------------
        | Load Image
        |--------------------------------------------------------------------------
        */

        $imagick = new Imagick($file);

        if ($imagick->getNumberImages() > 1) {
            $imagick->setIteratorIndex(0);
        }

        // Remember whether the source carried real transparency, so the
        // converted file can drop a meaningless alpha channel later.
        $source_had_alpha = $imagick->getImageAlphaChannel() !== Imagick::ALPHACHANNEL_UNDEFINED;

        /*
        |--------------------------------------------------------------------------
        | Auto Orientation
        |--------------------------------------------------------------------------
        */

        if (yio_get_option('auto_orientation', 1)) {
            yio_auto_orient($imagick);
        }

        /*
        |--------------------------------------------------------------------------
        | Smart Resize
        |--------------------------------------------------------------------------
        */

        if (yio_get_option('smart_resize', 1)) {

            $max_width = (int) yio_get_option('max_width', 2000);
            $geometry  = $imagick->getImageGeometry();

            if ($geometry['width'] > $max_width) {

                $imagick->resizeImage($max_width, 0, Imagick::FILTER_LANCZOS, 1);

                yio_log('Resized to max width ' . $max_width . ': ' . $file);
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Watermark (self-gating engine, Stage 2)
        |--------------------------------------------------------------------------
        */

        $imagick = yio_apply_watermark($imagick, $attachment_id);

        /*
        |--------------------------------------------------------------------------
        | SEO Optimization (self-gating engine, Stage 3)
        |--------------------------------------------------------------------------
        */

        $imagick = yio_apply_seo_optimization($imagick, $attachment_id);

        /*
        |--------------------------------------------------------------------------
        | Convert To Target Format
        |--------------------------------------------------------------------------
        */

        $quality = (int) yio_get_option('image_quality', 80);
        $target  = yio_output_extension();

        // Watermark and noise blending can introduce an alpha channel on
        // opaque sources (e.g. JPEG); drop it so the WebP/AVIF output
        // stays lean.
        if (!$source_had_alpha) {
            $imagick->setImageAlphaChannel(Imagick::ALPHACHANNEL_REMOVE);
        }

        $imagick->setImageFormat($target);
        $imagick->setImageCompressionQuality($quality);
        $imagick->setCompressionQuality($quality);

        $new_file = $dir . '/' . $base . '.' . $target;

        $written = $imagick->writeImage($new_file);

        $imagick->clear();
        $imagick->destroy();

        if (!$written) {
            yio_log('Could not write optimized file: ' . $new_file);
            return $metadata;
        }

        $created[] = $new_file;

        /*
        |--------------------------------------------------------------------------
        | Keep The Smaller File
        |--------------------------------------------------------------------------
        */

        $old_size = (int) filesize($file);
        $new_size = (int) filesize($new_file);

        if ($new_size >= $old_size) {

            @unlink($new_file);

            yio_log('Optimized file not smaller, keeping original: ' . $file
                . ' (' . size_format($old_size, 2) . ' -> ' . size_format($new_size, 2) . ')');

            return $metadata;
        }

        /*
        |--------------------------------------------------------------------------
        | Regenerate Sizes From The Optimized File
        |--------------------------------------------------------------------------
        */

        $new_metadata = wp_generate_attachment_metadata($attachment_id, $new_file);

        if (!is_array($new_metadata)) {
            throw new RuntimeException('Size regeneration returned an invalid result.');
        }

        if (!empty($new_metadata['sizes']) && is_array($new_metadata['sizes'])) {

            foreach ($new_metadata['sizes'] as $size) {

                if (empty($size['file'])) {
                    continue;
                }

                $created[] = $dir . '/' . $size['file'];
            }
        }

        if (empty($new_metadata['sizes']) && !empty($metadata['sizes'])) {
            yio_log('Warning: no size variants were generated for ' . basename($new_file));
        }

        /*
        |--------------------------------------------------------------------------
        | Point WordPress At The New File
        |--------------------------------------------------------------------------
        */

        $uploads  = wp_get_upload_dir();
        $new_url  = $uploads['baseurl'] . '/' . _wp_relative_upload_path($new_file);
        $filetype = wp_check_filetype($new_file);

        // Update the cosmetic fields first...
        wp_update_post(array(
            'ID'             => $attachment_id,
            'guid'           => $new_url,
            'post_mime_type' => !empty($filetype['type']) ? $filetype['type'] : 'image/webp',
        ));

        // ...then flip the attached-file pointer last, so a failure above
        // leaves the database fully pointed at the still-intact original.
        update_attached_file($attachment_id, $new_file);

    } catch (Throwable $e) {

        // Rollback: remove conversion artifacts, keep the original intact.
        foreach ($created as $created_file) {

            if (is_file($created_file)) {
                @unlink($created_file);
            }
        }

        yio_log('Optimization failed (' . $e->getMessage() . '): ' . $file);

        return $metadata;
    }

    /*
    |--------------------------------------------------------------------------
    | Remove Old Files (only after the database points at the new file)
    |--------------------------------------------------------------------------
    */

    if (!empty($metadata['sizes']) && is_array($metadata['sizes'])) {

        foreach ($metadata['sizes'] as $size) {

            if (empty($size['file'])) {
                continue;
            }

            $size_file = $dir . '/' . $size['file'];

            if (is_file($size_file)) {
                @unlink($size_file);
            }
        }
    }

    if (!empty($metadata['original_image'])) {

        $original_image = $dir . '/' . $metadata['original_image'];

        if (is_file($original_image)) {
            @unlink($original_image);
        }
    }

    @unlink($file);

    yio_log('Optimized: ' . basename($file) . ' -> ' . basename($new_file)
        . ' (' . size_format($old_size, 2) . ' -> ' . size_format($new_size, 2) . ')');

    return $new_metadata;
}

/*
|--------------------------------------------------------------------------
| Auto Orientation
|--------------------------------------------------------------------------
*/

/**
 * Apply EXIF orientation to the pixels and reset the orientation flag,
 * so the converted file always renders upright.
 *
 * @param Imagick $imagick
 * @return void
 */
function yio_auto_orient($imagick)
{
    $orientation = $imagick->getImageOrientation();

    if (
        $orientation === Imagick::ORIENTATION_UNDEFINED
        ||
        $orientation === Imagick::ORIENTATION_TOPLEFT
    ) {
        return;
    }

    switch ($orientation) {

        case Imagick::ORIENTATION_TOPRIGHT:
            $imagick->flopImage();
            break;

        case Imagick::ORIENTATION_BOTTOMRIGHT:
            $imagick->rotateImage('#000000', 180);
            break;

        case Imagick::ORIENTATION_BOTTOMLEFT:
            $imagick->flipImage();
            break;

        case Imagick::ORIENTATION_LEFTTOP:
            $imagick->transposeImage();
            break;

        case Imagick::ORIENTATION_RIGHTTOP:
            $imagick->rotateImage('#000000', 90);
            break;

        case Imagick::ORIENTATION_RIGHTBOTTOM:
            $imagick->transverseImage();
            break;

        case Imagick::ORIENTATION_LEFTBOTTOM:
            $imagick->rotateImage('#000000', 270);
            break;
    }

    $imagick->setImageOrientation(Imagick::ORIENTATION_TOPLEFT);
}

/*
|--------------------------------------------------------------------------
| Animated GIF Detection
|--------------------------------------------------------------------------
*/

/**
 * Detect animated GIFs so the pipeline can skip them instead of
 * flattening the animation into a single frame.
 *
 * @param string $file
 * @return bool
 */
function yio_is_animated_gif($file)
{
    try {

        $imagick = new Imagick($file);

        $count = $imagick->getNumberImages();

        $imagick->clear();
        $imagick->destroy();

    } catch (Throwable $e) {

        return false;

    }

    return $count > 1;
}
